export const ADD_TEAM="ADD_TEAM"
export const ADD_PLAYER="ADD_PLAYER"
export const DELETE_PLAYER="DELETE_PLAYER"
export const ADD_PASSWORD_ROUND="ADD_PASSWORD_ROUND"
export const ADD_GUESS_ANSWER="ADD_GUESS_ANSWER"
export const CHECK_ANSWER="CHECK_ANSWER"
export const SHOW_CORRECT_ANSWER="SHOW_CORRECT_ANSWER"

export const INTERCEPTION_LIST="INTERCEPTION_LIST"